
     google.load('visualization', '1', {'packages': ['geochart']});
     google.setOnLoadCallback(drawRegionsMap);

      function drawRegionsMap() {
        var data = google.visualization.arrayToDataTable([
          ['Country', 'Infrastructure Index'],

        ['Algeria', 40.0] ,
        ['Angola', 26.0] ,
        ['Benin', 26.0] ,
        ['Botswana', 35.0] ,
        ['Burkina Faso', 27.0] ,
        ['Burundi', 20.0] ,
        ['Cameroon', 23.0] ,
        ['Cape Verde', 35.0] ,
        ['Central African Republic', 17.0] ,
        ['Chad', 10.0] ,
        ['Comoros', 34.0] ,
        ['D R Congo', 9.0] ,
        ['Djibouti', 32.0] ,
        ['Egypt', 37.0] ,
        ['Equatorial Guinea', 35.0] ,
        ['Eritrea', 22.0] ,
        ['Ethiopia', 16.0] ,
        ['Gabon', 37.0] ,
        ['Gambia', 30.0] ,
        ['Ghana', 32.0] ,
        ['Guinea', 18.0] ,
        ['Gunea-Bissau', 19.0] ,
        ['Ivory Coast', 18.0] ,
        ['Kenya', 17.0] ,
        ['Lesotho', 30.0] ,
        ['Liberia', 18.0] ,
        ['Libya', 44.0] ,
        ['Madagascar', 35.0] ,
        ['Malawi', 23.0] ,
        ['Mali', 26.0] ,
        ['Mauritania', 30.0] ,
        ['Mauritius', 68.0] ,
        ['Morocco', 37.0] ,
        ['Mozambique', 27.0] ,
        ['Namibia', 35.0] ,
        ['Niger', 21.0] ,
        ['Nigeria', 21.0] ,
        ['Republic of the Congo', 23.0] ,
        ['Rwanda', 23.0] ,
        ['Sao Tome and Principe', 37.0] ,
        ['Senegal', 29.0] ,
        ['Seychelles', 55.0] ,
        ['Sierra Leone', 17.0] ,
        ['Somalia', 4.0] ,
        ['South Africa', 39.0] ,
        ['South Sudan', 14.0] ,
        ['Sudan', 17.0] ,
        ['Swaziland', 32.0] ,
        ['Tanzania', 25.0] ,
        ['Togo', 25.0] ,
        ['Tunisia', 51.0] ,
        ['Uganda', 19.0] ,
        ['Zambia', 22.0] ,
        ['Zimbabwe', 11.0] ,
        ['Africa Average', 27.79245] ,
        ['Afghanistan', 15.0] ,
        ['Bahrain', 68.0] ,
        ['Bangladesh', 24.0] ,
        ['Bhutan', 34.0] ,
        ['Brunei', 61.0] ,
        ['Burma (Myanmar)', 24.0] ,
        ['Cambodia', 26.0] ,
        ['China', 36.0] ,
        ['East Timor', 23.0] ,
        ['India', 36.0] ,
        ['Indonesia', 34.0] ,
        ['Iran', 37.0] ,
        ['Iraq', 18.0] ,
        ['Israel/West Bank', 41.0] ,
        ['Japan', 51.0] ,
        ['Jordan', 43.0] ,
        ['Kazakhstan', 55.0] ,
        ['Kuwait', 62.0] ,
        ['Kyrgyzstan', 40.0] ,
        ['Laos', 30.0] ,
        ['Lebanon', 34.0] ,
        ['Malaysia', 51.0] ,
        ['Maldives', 39.0] ,
        ['Mongolia', 61.0] ,
        ['Nepal', 28.0] ,
        ['Oman', 67.0] ,
        ['Pakistan', 21.0] ,
        ['Philippines', 34.0] ,
        ['Qatar', 71.0] ,
        ['Russia', 46.0] ,
        ['Saudi Arabia', 54.0] ,
        ['Singapore', 78.0] ,
        ['Sri Lanka', 28.0] ,
        ['Syria', 31.0] ,
        ['Tajikistan', 37.0] ,
        ['Thailand', 41.0] ,
        ['Turkey', 43.0] ,
        ['Turkmenistan', 47.0] ,
        ['United Arab Emirates', 68.0] ,
        ['Uzbekistan', 39.0] ,
        ['Vietnam', 43.0] ,
        ['Yemen', 16.0] ,
        ['Asia Average', 41.30952] ,
        ['Albania', 51.0] ,
        ['Armenia', 42.0] ,
        ['Austria', 78.0] ,
        ['Azerbaijan', 41.0] ,
        ['Belarus', 52.0] ,
        ['Belgium', 78.0] ,
        ['Bosnia and Herzegovina', 46.0] ,
        ['Bulgaria', 58.0] ,
        ['Croatia', 57.0] ,
        ['Cyprus', 58.0] ,
        ['Czech Republic', 68.0] ,
        ['Denmark', 78.0] ,
        ['Estonia', 63.0] ,
        ['Finland', 79.0] ,
        ['France', 77.0] ,
        ['Georgia', 41.0] ,
        ['Germany', 73.0] ,
        ['Greece', 62.0] ,
        ['Hungary', 67.0] ,
        ['Iceland', 80.0] ,
        ['Ireland', 76.0] ,
        ['Italy', 69.0] ,
        ['Latvia', 61.0] ,
        ['Lithuania', 64.0] ,
        ['Luxembourg', 81.0] ,
        ['Macedonia', 51.0] ,
        ['Malta', 62.0] ,
        ['Moldova', 41.0] ,
        ['Montenegro', 62.0] ,
        ['Netherlands', 75.0] ,
        ['Norway', 82.0] ,
        ['Poland', 62.0] ,
        ['Portugal', 71.0] ,
        ['Romania', 58.0] ,
        ['Serbia', 48.0] ,
        ['Slovakia', 65.0] ,
        ['Slovenia', 74.0] ,
        ['Spain', 73.0] ,
        ['Sweden', 78.0] ,
        ['Switzerland', 80.0] ,
        ['Ukraine', 55.0] ,
        ['United Kingdom', 73.0] ,
        ['Europe Average', 64.52381] ,
        ['Antigua and Barbuda', 50.0] ,
        ['Bahamas', 53.0] ,
        ['Barbados', 59.0] ,
        ['Belize', 38.0] ,
        ['Canada', 76.0] ,
        ['Costa Rica', 58.0] ,
        ['Cuba', 43.0] ,
        ['Dominican Republic', 35.0] ,
        ['El Salvador', 33.0] ,
        ['Grenada', 49.0] ,
        ['Guatemala', 34.0] ,
        ['Haiti', 11.0] ,
        ['Honduras', 39.0] ,
        ['Jamaica', 46.0] ,
        ['Mexico', 44.0] ,
        ['Nicaragua', 37.0] ,
        ['Panama', 52.0] ,
        ['Trinidad and Tobago', 47.0] ,
        ['United States', 75.0] ,
        ['North America Average', 46.26316] ,
        ['Australia', 73.0] ,
        ['Fiji', 69.0] ,
        ['Micronesia', 38.0] ,
        ['New Zealand', 78.0] ,
        ['Papua New Guinea', 30.0] ,
        ['Samoa', 43.0] ,
        ['Solomon Islands', 36.0] ,
        ['Ocenia Average', 52.42857] ,
        ['Argentina', 65.0] ,
        ['Bolivia', 38.0] ,
        ['Brazil', 48.0] ,
        ['Chile', 63.0] ,
        ['Colombia', 29.0] ,
        ['Ecuador', 35.0] ,
        ['Guyana', 40.0] ,
        ['Paraguay', 52.0] ,
        ['Peru', 41.0] ,
        ['Suriname', 47.0] ,
        ['Uruguay', 64.0] ,
        ['Venezuela', 43.0] ,
        ['South America Average', 47.08333] 
        ]);

        var options = { width: 1200, height: 800 };

        var chart = new google.visualization.GeoChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    };
    
