
     google.load('visualization', '1', {'packages': ['geochart']});
     google.setOnLoadCallback(drawRegionsMap);

      function drawRegionsMap() {
        var data = google.visualization.arrayToDataTable([
          ['Country', 'Government Legitimacy'],

        ['Algeria', 33.0] ,
        ['Angola', 31.0] ,
        ['Benin', 35.0] ,
        ['Botswana', 58.0] ,
        ['Burkina Faso', 25.0] ,
        ['Burundi', 18.0] ,
        ['Cameroon', 19.0] ,
        ['Cape Verde', 35.0] ,
        ['Central African Republic', 7.0] ,
        ['Chad', 9.0] ,
        ['Comoros', 22.0] ,
        ['D R Congo', 4.0] ,
        ['Djibouti', 26.0] ,
        ['Egypt', 17.0] ,
        ['Equatorial Guinea', 22.0] ,
        ['Eritrea', 18.0] ,
        ['Ethiopia', 19.0] ,
        ['Gabon', 35.0] ,
        ['Gambia', 31.0] ,
        ['Ghana', 54.0] ,
        ['Guinea', 11.0] ,
        ['Gunea-Bissau', 8.0] ,
        ['Ivory Coast', 4.0] ,
        ['Kenya', 16.0] ,
        ['Lesotho', 36.0] ,
        ['Liberia', 21.0] ,
        ['Libya', 15.0] ,
        ['Madagascar', 25.0] ,
        ['Malawi', 27.0] ,
        ['Mali', 40.0] ,
        ['Mauritania', 30.0] ,
        ['Mauritius', 61.0] ,
        ['Morocco', 37.0] ,
        ['Mozambique', 34.0] ,
        ['Namibia', 51.0] ,
        ['Niger', 16.0] ,
        ['Nigeria', 13.0] ,
        ['Republic of the Congo', 24.0] ,
        ['Rwanda', 30.0] ,
        ['Sao Tome and Principe', 35.0] ,
        ['Senegal', 38.0] ,
        ['Seychelles', 37.0] ,
        ['Sierra Leone', 29.0] ,
        ['Somalia', 1.0] ,
        ['South Africa', 53.0] ,
        ['South Sudan', 3.0] ,
        ['Sudan', 4.0] ,
        ['Swaziland', 27.0] ,
        ['Tanzania', 36.0] ,
        ['Togo', 25.0] ,
        ['Tunisia', 27.0] ,
        ['Uganda', 17.0] ,
        ['Zambia', 34.0] ,
        ['Zimbabwe', 11.0] ,
        ['Africa Average', 26.30189] ,
        ['Afghanistan', 3.0] ,
        ['Bahrain', 34.0] ,
        ['Bangladesh', 23.0] ,
        ['Bhutan', 33.0] ,
        ['Brunei', 38.0] ,
        ['Burma (Myanmar)', 19.0] ,
        ['Cambodia', 24.0] ,
        ['China', 39.0] ,
        ['East Timor', 15.0] ,
        ['India', 38.0] ,
        ['Indonesia', 32.0] ,
        ['Iran', 15.0] ,
        ['Iraq', 8.0] ,
        ['Israel/West Bank', 26.0] ,
        ['Japan', 72.0] ,
        ['Jordan', 38.0] ,
        ['Kazakhstan', 32.0] ,
        ['Kuwait', 42.0] ,
        ['Kyrgyzstan', 20.0] ,
        ['Laos', 23.0] ,
        ['Lebanon', 18.0] ,
        ['Malaysia', 39.0] ,
        ['Maldives', 31.0] ,
        ['Mongolia', 43.0] ,
        ['Nepal', 22.0] ,
        ['Oman', 47.0] ,
        ['Pakistan', 10.0] ,
        ['Philippines', 25.0] ,
        ['Qatar', 55.0] ,
        ['Russia', 29.0] ,
        ['Saudi Arabia', 28.0] ,
        ['Singapore', 70.0] ,
        ['Sri Lanka', 20.0] ,
        ['Syria', 13.0] ,
        ['Tajikistan', 23.0] ,
        ['Thailand', 31.0] ,
        ['Turkey', 32.0] ,
        ['Turkmenistan', 28.0] ,
        ['United Arab Emirates', 57.0] ,
        ['Uzbekistan', 22.0] ,
        ['Vietnam', 35.0] ,
        ['Yemen', 7.0] ,
        ['Asia Average', 29.97619] ,
        ['Albania', 37.0] ,
        ['Armenia', 37.0] ,
        ['Austria', 82.0] ,
        ['Azerbaijan', 26.0] ,
        ['Belarus', 24.0] ,
        ['Belgium', 72.0] ,
        ['Bosnia and Herzegovina', 25.0] ,
        ['Bulgaria', 49.0] ,
        ['Croatia', 53.0] ,
        ['Cyprus', 33.0] ,
        ['Czech Republic', 68.0] ,
        ['Denmark', 85.0] ,
        ['Estonia', 60.0] ,
        ['Finland', 89.0] ,
        ['France', 81.0] ,
        ['Georgia', 16.0] ,
        ['Germany', 80.0] ,
        ['Greece', 66.0] ,
        ['Hungary', 57.0] ,
        ['Iceland', 75.0] ,
        ['Ireland', 81.0] ,
        ['Italy', 58.0] ,
        ['Latvia', 58.0] ,
        ['Lithuania', 68.0] ,
        ['Luxembourg', 74.0] ,
        ['Macedonia', 38.0] ,
        ['Malta', 65.0] ,
        ['Moldova', 25.0] ,
        ['Montenegro', 48.0] ,
        ['Netherlands', 83.0] ,
        ['Norway', 84.0] ,
        ['Poland', 66.0] ,
        ['Portugal', 79.0] ,
        ['Romania', 52.0] ,
        ['Serbia', 29.0] ,
        ['Slovakia', 73.0] ,
        ['Slovenia', 76.0] ,
        ['Spain', 64.0] ,
        ['Sweden', 84.0] ,
        ['Switzerland', 87.0] ,
        ['Ukraine', 34.0] ,
        ['United Kingdom', 75.0] ,
        ['Europe Average', 59.90476] ,
        ['Antigua and Barbuda', 50.0] ,
        ['Bahamas', 54.0] ,
        ['Barbados', 57.0] ,
        ['Belize', 45.0] ,
        ['Canada', 84.0] ,
        ['Costa Rica', 63.0] ,
        ['Cuba', 33.0] ,
        ['Dominican Republic', 41.0] ,
        ['El Salvador', 45.0] ,
        ['Grenada', 39.0] ,
        ['Guatemala', 36.0] ,
        ['Haiti', 9.0] ,
        ['Honduras', 33.0] ,
        ['Jamaica', 44.0] ,
        ['Mexico', 35.0] ,
        ['Nicaragua', 32.0] ,
        ['Panama', 60.0] ,
        ['Trinidad and Tobago', 45.0] ,
        ['United States', 77.0] ,
        ['North America Average', 46.42105] ,
        ['Australia', 85.0] ,
        ['Fiji', 24.0] ,
        ['Micronesia', 36.0] ,
        ['New Zealand', 90.0] ,
        ['Papua New Guinea', 32.0] ,
        ['Samoa', 38.0] ,
        ['Solomon Islands', 23.0] ,
        ['Ocenia Average', 46.85714] ,
        ['Argentina', 65.0] ,
        ['Bolivia', 30.0] ,
        ['Brazil', 49.0] ,
        ['Chile', 71.0] ,
        ['Colombia', 26.0] ,
        ['Ecuador', 29.0] ,
        ['Guyana', 41.0] ,
        ['Paraguay', 36.0] ,
        ['Peru', 36.0] ,
        ['Suriname', 39.0] ,
        ['Uruguay', 68.0] ,
        ['Venezuela', 32.0] ,
        ['South America Average', 43.5],
        ]);

        var options = { width: 1200, height: 800 };

        var chart = new google.visualization.GeoChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    };
   
