
google.load('visualization', '1', {'packages': ['geochart']});
google.setOnLoadCallback(drawRegionsMap);

      function drawRegionsMap() {
        var data = google.visualization.arrayToDataTable([
          ['Country', 'Economic Equality'],
 -->
        ['Algeria', 35.0] ,
        ['Angola', 9.0] ,
        ['Benin', 31.0] ,
        ['Botswana', 23.0] ,
        ['Burkina Faso', 18.0] ,
        ['Burundi', 21.0] ,
        ['Cameroon', 19.0] ,
        ['Cape Verde', 34.0] ,
        ['Central African Republic', 13.0] ,
        ['Chad', 14.0] ,
        ['Comoros', 39.0] ,
        ['D R Congo', 11.0] ,
        ['Djibouti', 29.0] ,
        ['Egypt', 26.0] ,
        ['Equatorial Guinea', 12.0] ,
        ['Eritrea', 31.0] ,
        ['Ethiopia', 21.0] ,
        ['Gabon', 24.0] ,
        ['Gambia', 35.0] ,
        ['Ghana', 38.0] ,
        ['Guinea', 19.0] ,
        ['Gunea-Bissau', 22.0] ,
        ['Ivory Coast', 23.0] ,
        ['Kenya', 18.0] ,
        ['Lesotho', 36.0] ,
        ['Liberia', 23.0] ,
        ['Libya', 30.0] ,
        ['Madagascar', 24.0] ,
        ['Malawi', 23.0] ,
        ['Mali', 36.0] ,
        ['Mauritania', 37.0] ,
        ['Mauritius', 49.0] ,
        ['Morocco', 28.0] ,
        ['Mozambique', 23.0] ,
        ['Namibia', 15.0] ,
        ['Niger', 24.0] ,
        ['Nigeria', 11.0] ,
        ['Republic of the Congo', 21.0] ,
        ['Rwanda', 26.0] ,
        ['Sao Tome and Principe', 39.0] ,
        ['Senegal', 31.0] ,
        ['Seychelles', 31.0] ,
        ['Sierra Leone', 18.0] ,
        ['Somalia', 19.0] ,
        ['South Africa', 18.0] ,
        ['South Sudan', 12.0] ,
        ['Sudan', 12.0] ,
        ['Swaziland', 30.0] ,
        ['Tanzania', 41.0] ,
        ['Togo', 24.0] ,
        ['Tunisia', 37.0] ,
        ['Uganda', 19.0] ,
        ['Zambia', 23.0] ,
        ['Zimbabwe', 11.0] ,
        ['Africa Average', 25.20755] ,
        ['Afghanistan', 19.0] ,
        ['Bahrain', 43.0] ,
        ['Bangladesh', 19.0] ,
        ['Bhutan', 22.0] ,
        ['Brunei', 22.0] ,
        ['Burma (Myanmar)', 13.0] ,
        ['Cambodia', 29.0] ,
        ['China', 17.0] ,
        ['East Timor', 30.0] ,
        ['India', 16.0] ,
        ['Indonesia', 28.0] ,
        ['Iran', 33.0] ,
        ['Iraq', 13.0] ,
        ['Israel/West Bank', 22.0] ,
        ['Japan', 80.0] ,
        ['Jordan', 32.0] ,
        ['Kazakhstan', 44.0] ,
        ['Kuwait', 44.0] ,
        ['Kyrgyzstan', 27.0] ,
        ['Laos', 42.0] ,
        ['Lebanon', 35.0] ,
        ['Malaysia', 36.0] ,
        ['Maldives', 53.0] ,
        ['Mongolia', 40.0] ,
        ['Nepal', 16.0] ,
        ['Oman', 67.0] ,
        ['Pakistan', 18.0] ,
        ['Philippines', 32.0] ,
        ['Qatar', 52.0] ,
        ['Russia', 27.0] ,
        ['Saudi Arabia', 33.0] ,
        ['Singapore', 63.0] ,
        ['Sri Lanka', 19.0] ,
        ['Syria', 25.0] ,
        ['Tajikistan', 35.0] ,
        ['Thailand', 31.0] ,
        ['Turkey', 29.0] ,
        ['Turkmenistan', 32.0] ,
        ['United Arab Emirates', 49.0] ,
        ['Uzbekistan', 21.0] ,
        ['Vietnam', 41.0] ,
        ['Yemen', 16.0] ,
        ['Asia Average', 32.5] ,
        ['Albania', 49.0] ,
        ['Armenia', 41.0] ,
        ['Austria', 59.0] ,
        ['Azerbaijan', 34.0] ,
        ['Belarus', 40.0] ,
        ['Belgium', 59.0] ,
        ['Bosnia and Herzegovina', 35.0] ,
        ['Bulgaria', 46.0] ,
        ['Croatia', 53.0] ,
        ['Cyprus', 30.0] ,
        ['Czech Republic', 65.0] ,
        ['Denmark', 82.0] ,
        ['Estonia', 54.0] ,
        ['Finland', 87.0] ,
        ['France', 54.0] ,
        ['Georgia', 34.0] ,
        ['Germany', 59.0] ,
        ['Greece', 54.0] ,
        ['Hungary', 48.0] ,
        ['Iceland', 81.0] ,
        ['Ireland', 73.0] ,
        ['Italy', 62.0] ,
        ['Latvia', 46.0] ,
        ['Lithuania', 46.0] ,
        ['Luxembourg', 82.0] ,
        ['Macedonia', 35.0] ,
        ['Malta', 62.0] ,
        ['Moldova', 38.0] ,
        ['Montenegro', 62.0] ,
        ['Netherlands', 74.0] ,
        ['Norway', 82.0] ,
        ['Poland', 56.0] ,
        ['Portugal', 63.0] ,
        ['Romania', 44.0] ,
        ['Serbia', 38.0] ,
        ['Slovakia', 51.0] ,
        ['Slovenia', 56.0] ,
        ['Spain', 56.0] ,
        ['Sweden', 81.0] ,
        ['Switzerland', 74.0] ,
        ['Ukraine', 44.0] ,
        ['United Kingdom', 61.0] ,
        ['Europe Average', 55.95238] ,
        ['Antigua and Barbuda', 44.0] ,
        ['Bahamas', 41.0] ,
        ['Barbados', 40.0] ,
        ['Belize', 31.0] ,
        ['Canada', 62.0] ,
        ['Costa Rica', 36.0] ,
        ['Cuba', 41.0] ,
        ['Dominican Republic', 28.0] ,
        ['El Salvador', 27.0] ,
        ['Grenada', 38.0] ,
        ['Guatemala', 24.0] ,
        ['Haiti', 14.0] ,
        ['Honduras', 19.0] ,
        ['Jamaica', 38.0] ,
        ['Mexico', 25.0] ,
        ['Nicaragua', 18.0] ,
        ['Panama', 25.0] ,
        ['Trinidad and Tobago', 34.0] ,
        ['United States', 49.0] ,
        ['North America Average', 33.36842] ,
        ['Australia', 64.0] ,
        ['Fiji', 23.0] ,
        ['Micronesia', 25.0] ,
        ['New Zealand', 63.0] ,
        ['Papua New Guinea', 12.0] ,
        ['Samoa', 37.0] ,
        ['Solomon Islands', 17.0] ,
        ['Ocenia Average', 34.42857] ,
        ['Argentina', 37.0] ,
        ['Bolivia', 12.0] ,
        ['Brazil', 16.0] ,
        ['Chile', 45.0] ,
        ['Colombia', 16.0] ,
        ['Ecuador', 23.0] ,
        ['Guyana', 29.0] ,
        ['Paraguay', 17.0] ,
        ['Peru', 20.0] ,
        ['Suriname', 25.0] ,
        ['Uruguay', 54.0] ,
        ['Venezuela', 28.0] ,
        ['South America Average', 26.83333]
        ]);

        var options = { width: 1200, height: 800 };

        var chart = new google.visualization.GeoChart(document.getElementById('chart_div'));
        chart.draw(data, options);
};
