
     google.load('visualization', '1', {'packages': ['geochart']});
     google.setOnLoadCallback(drawRegionsMap);

      function drawRegionsMap() {
        var data = google.visualization.arrayToDataTable([
          ['Country', 'Human Rights Index'],
        
        ['Algeria', 22.0] ,
        ['Angola', 29.0] ,
        ['Benin', 55.0] ,
        ['Botswana', 52.0] ,
        ['Burkina Faso', 39.0] ,
        ['Burundi', 19.0] ,
        ['Cameroon', 23.0] ,
        ['Cape Verde', 52.0] ,
        ['Central African Republic', 15.0] ,
        ['Chad', 8.0] ,
        ['Comoros', 42.0] ,
        ['D R Congo', 5.0] ,
        ['Djibouti', 33.0] ,
        ['Egypt', 11.0] ,
        ['Equatorial Guinea', 21.0] ,
        ['Eritrea', 24.0] ,
        ['Ethiopia', 16.0] ,
        ['Gabon', 49.0] ,
        ['Gambia', 44.0] ,
        ['Ghana', 51.0] ,
        ['Guinea', 17.0] ,
        ['Gunea-Bissau', 34.0] ,
        ['Ivory Coast', 13.0] ,
        ['Kenya', 18.0] ,
        ['Lesotho', 48.0] ,
        ['Liberia', 37.0] ,
        ['Libya', 20.0] ,
        ['Madagascar', 44.0] ,
        ['Malawi', 36.0] ,
        ['Mali', 47.0] ,
        ['Mauritania', 26.0] ,
        ['Mauritius', 63.0] ,
        ['Morocco', 34.0] ,
        ['Mozambique', 42.0] ,
        ['Namibia', 46.0] ,
        ['Niger', 22.0] ,
        ['Nigeria', 8.0] ,
        ['Republic of the Congo', 32.0] ,
        ['Rwanda', 17.0] ,
        ['Sao Tome and Principe', 53.0] ,
        ['Senegal', 37.0] ,
        ['Seychelles', 48.0] ,
        ['Sierra Leone', 37.0] ,
        ['Somalia', 2.0] ,
        ['South Africa', 49.0] ,
        ['South Sudan', 4.0] ,
        ['Sudan', 6.0] ,
        ['Swaziland', 40.0] ,
        ['Tanzania', 38.0] ,
        ['Togo', 37.0] ,
        ['Tunisia', 30.0] ,
        ['Uganda', 22.0] ,
        ['Zambia', 36.0] ,
        ['Zimbabwe', 12.0] ,
        ['Africa Average', 31.41509] ,
        ['Afghanistan', 10.0] ,
        ['Bahrain', 28.0] ,
        ['Bangladesh', 21.0] ,
        ['Bhutan', 25.0] ,
        ['Brunei', 36.0] ,
        ['Burma (Myanmar)', 13.0] ,
        ['Cambodia', 25.0] ,
        ['China', 17.0] ,
        ['East Timor', 34.0] ,
        ['India', 31.0] ,
        ['Indonesia', 30.0] ,
        ['Iran', 12.0] ,
        ['Iraq', 10.0] ,
        ['Israel/West Bank', 13.0] ,
        ['Japan', 65.0] ,
        ['Jordan', 30.0] ,
        ['Kazakhstan', 32.0] ,
        ['Kuwait', 44.0] ,
        ['Kyrgyzstan', 19.0] ,
        ['Laos', 27.0] ,
        ['Lebanon', 25.0] ,
        ['Malaysia', 31.0] ,
        ['Maldives', 38.0] ,
        ['Mongolia', 53.0] ,
        ['Nepal', 14.0] ,
        ['Oman', 45.0] ,
        ['Pakistan', 9.0] ,
        ['Philippines', 27.0] ,
        ['Qatar', 49.0] ,
        ['Russia', 20.0] ,
        ['Saudi Arabia', 18.0] ,
        ['Singapore', 60.0] ,
        ['Sri Lanka', 11.0] ,
        ['Syria', 7.0] ,
        ['Tajikistan', 23.0] ,
        ['Thailand', 24.0] ,
        ['Turkey', 27.0] ,
        ['Turkmenistan', 26.0] ,
        ['United Arab Emirates', 49.0] ,
        ['Uzbekistan', 16.0] ,
        ['Vietnam', 33.0] ,
        ['Yemen', 13.0] ,
        ['Asia Average', 27.14286] ,
        ['Albania', 47.0] ,
        ['Armenia', 37.0] ,
        ['Austria', 71.0] ,
        ['Azerbaijan', 27.0] ,
        ['Belarus', 26.0] ,
        ['Belgium', 70.0] ,
        ['Bosnia and Herzegovina', 30.0] ,
        ['Bulgaria', 55.0] ,
        ['Croatia', 49.0] ,
        ['Cyprus', 47.0] ,
        ['Czech Republic', 69.0] ,
        ['Denmark', 77.0] ,
        ['Estonia', 58.0] ,
        ['Finland', 86.0] ,
        ['France', 58.0] ,
        ['Georgia', 25.0] ,
        ['Germany', 68.0] ,
        ['Greece', 59.0] ,
        ['Hungary', 65.0] ,
        ['Iceland', 87.0] ,
        ['Ireland', 85.0] ,
        ['Italy', 59.0] ,
        ['Latvia', 56.0] ,
        ['Lithuania', 65.0] ,
        ['Luxembourg', 79.0] ,
        ['Macedonia', 39.0] ,
        ['Malta', 64.0] ,
        ['Moldova', 37.0] ,
        ['Montenegro', 44.0] ,
        ['Netherlands', 73.0] ,
        ['Norway', 71.0] ,
        ['Poland', 65.0] ,
        ['Portugal', 73.0] ,
        ['Romania', 49.0] ,
        ['Serbia', 31.0] ,
        ['Slovakia', 57.0] ,
        ['Slovenia', 69.0] ,
        ['Spain', 59.0] ,
        ['Sweden', 87.0] ,
        ['Switzerland', 74.0] ,
        ['Ukraine', 42.0] ,
        ['United Kingdom', 66.0] ,
        ['Europe Average', 58.45238] ,
        ['Antigua and Barbuda', 55.0] ,
        ['Bahamas', 62.0] ,
        ['Barbados', 64.0] ,
        ['Belize', 58.0] ,
        ['Canada', 75.0] ,
        ['Costa Rica', 64.0] ,
        ['Cuba', 39.0] ,
        ['Dominican Republic', 41.0] ,
        ['El Salvador', 38.0] ,
        ['Grenada', 60.0] ,
        ['Guatemala', 31.0] ,
        ['Haiti', 26.0] ,
        ['Honduras', 41.0] ,
        ['Jamaica', 54.0] ,
        ['Mexico', 40.0] ,
        ['Nicaragua', 40.0] ,
        ['Panama', 53.0] ,
        ['Trinidad and Tobago', 50.0] ,
        ['United States', 63.0] ,
        ['North America Average', 50.21053] ,
        ['Australia', 69.0] ,
        ['Fiji', 27.0] ,
        ['Micronesia', 65.0] ,
        ['New Zealand', 73.0] ,
        ['Papua New Guinea', 35.0] ,
        ['Samoa', 54.0] ,
        ['Solomon Islands', 35.0] ,
        ['Ocenia Average', 51.14286] ,
        ['Argentina', 57.0] ,
        ['Bolivia', 30.0] ,
        ['Brazil', 44.0] ,
        ['Chile', 65.0] ,
        ['Colombia', 29.0] ,
        ['Ecuador', 39.0] ,
        ['Guyana', 45.0] ,
        ['Paraguay', 38.0] ,
        ['Peru', 40.0] ,
        ['Suriname', 43.0] ,
        ['Uruguay', 73.0] ,
        ['Venezuela', 28.0] ,
        ['South America Average', 44.25]
        ]);

        var options = { width: 1200, height: 800 };

        var chart = new google.visualization.GeoChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    };
    
